- app/templates/partials/header.html
The respondent home ui code has been cloned to create this new respondent home repo for Census. The banner has been changed to show the code is in development for Census.
Banner changed from 'My Study' to 'Census Dress Rehearsal 2019 (Banner TBD)'
in header.html 
No
The code has been run locally and the banner change confirmed.
> CR-25 Change banner from My Study to Census Dress Rehearsal 2019 TBD

- app/__init__.py
- app/handlers.py
- app/sample.py
- app/templates/address-edit.html
Initial implementation of screen to edit address fields for Cen-0046 Incorrect Address.  
A screen to edit the address returned from the sample service is displayed with the current address and the changed address is then sent to EQ. Note, this changed address is not stored against the case and subsequent user stories are thought to deal with classifying these new address details into type of change and what action the system needs to take.
Tested against all other services running in Docker. 
https://collaborate2.ons.gov.uk/confluence/display/CRM/Cen-0046%2C+Incorrect+Address
> CEN-0046 Incorrect Address

- ci/integration_tests.sh
- ci/integration_tests.yml
- ci/smoke_tests.sh
- ci/smoke_tests.yml
Smoke and Int test Pipelines in the project needed changing 
Pipelines
Execute latest-deploy pipeline in concourse
> CDTT-459 smoke and int test pipelines

- app/templates/base.html
- app/templates/closed.html
- app/templates/completed.html
panle colours reinstated and correct
Colours for panels have been changed. References to study removed.
> CDTT-776 - Panel colour changed

- tests/unit/test_handlers.py
Fix unit tests broken by changing study to survey
test-handlers.py has been changed to check for survey instead of study
run make test
> CDTT-776-change_panel_color

- app/templates/partials/footer.html
All links in footer to be removed until is has been confirmed what links are required. 
All footer links removed. Headers remain.
Run RH and check footers are no longer present.
> CR163 - Footer links removed

- .gitignore
- app/handlers.py
- tests/test_data/rhsvc/uac.json
- tests/unit/__init__.py
- tests/unit/test_handlers.py
Implement post to surveyLaunched endpoint before eq launch point
Added endpoint post in
Refactor of post methods, and update of appropriate tests
Refactor of iac variable names to uac throughout
Tests updated so can be run via make test as usual
> Cr130 survey launched

- app/templates/webchat-form.html
Minor fix to deployed web chat
Update to html template
Unaffected
None
None
> Fix so country maintains value

- app/error_handlers.py
- app/handlers.py
Fixed welsh language test against fulfilment code
Code error found in both request code paths when returning welsh address
Fixed language matching value (matches to fixed value rather than 'display_region' which is a different format), and added missing KeyError trap
Change return values in local rhsvc
> Cr488 request language bug

- app/config.py
- app/eq.py
- tests/test_data/local.env
Implemented with new CONFIG values for domain_url
Update so urls for EQ build with environment specific domain values
Added and used 2 new domain_url configs
Updated unit tests
Check values submitted in EQ payload
None
None
> Cr487 revisit

- app/config.py
- app/eq.py
Fix
EQ payload urls not getting protocol on url
New config value added with default value
Unit tests pass
> CR487 EQ URL BUG

- app/templates/404.html
- app/templates/error.html
- app/templates/request-code-not-required.html
- app/templates/request-code-select-address.html
- app/templates/webchat-form.html
Updated remaining links in unhappy paths to help site content
Setting of real destinations for links
Links only active whitelodge and further (link to campaign website)
> CR478 - Add in remaining missing links

- scripts/load_templates.sh
Update to design pattern 13.6.8
Update to design pattern 13.6.8
N/A
> CR529 Update to design pattern 13.6.8

- app/handlers.py
- scripts/load_templates.sh
Up design pattern to 13.6.9
Design pattern version
N/A
> CR532 - Update to design pattern (to 13.6.9), fix 2 pep8 issues

- app/templates/base-cy.html
- app/templates/base-en.html
- app/templates/base-ni.html
- app/templates/base-start-cy.html
- app/templates/base-start-en.html
- app/templates/base-start-ni.html
- app/templates/base-webchat-cy.html
- app/templates/base-webchat-en.html
- app/templates/base-webchat-ni.html
- app/templates/index.html
- app/templates/request-code-household.html
- app/templates/request-code-individual.html
- scripts/load_templates.sh
Updates RHUI to the current version of the design patterns
Update to version 14.3.0 of the design patterns
Change 'set page' to 'set pageConfig' to bring into line with breaking change in design pattern update
Removed unnecessary set page title from index.html
Removed no longer needed closed message calls in start, request household, and request individual pages
User must run scripts/load_templates.sh to update to new templates
Unit tests pass
N/A
> CR-655 - Updated to design pattern 14.3.0.

- app/requests_handlers.py
- tests/unit/test_requests_handlers.py
Update to work with new product representation
Added productGroup and individual params to get_fulfilments call
Added logic to set value for individual flag, and set caseType to HH for individual
Tweaks to unit tests
Tested with updated RHSvc in dev environment
https://collaborate2.ons.gov.uk/jira/browse/CR-764
> CR-764 RHUI New Product Representation

- app/handlers.py
- app/templates/start-launch-eq.html
Initial push for proof of concept
PoC for Serco endpoint, to test in WL
New page and handler to accept token from CC in query string.
Clicking button on page will trigger EQ launch with token provided.
URL is /en/start/launch-eq/?token=
Will work with /cy and /ni, although has no effect on EQ
Use url with a token value, press button, EQ should launch
Full unit tests etc to follow
> CR-000 Serco Redirect

- app/start_handlers.py
- app/webchat_handlers.py
This ticket involved reviewing the logging in RHUI. There were some points raised regarding it and was discussed and agreed with Paul and the changes have been made accordingly.
For more information please see the ticket https://collaborate2.ons.gov.uk/jira/browse/CR-1257. 
To know more about the context of the changes please look at the **Questions** tab in the spreadsheet attached to this ticket and Paul's response on the ticket.
> CR-1257 | tidying up the logging

- app/app_logging.py
- app/handlers.py
Following changes are made:
1) Removing logging for /info
2) Timestamp logging changed to milliseconds
> CR-1257 | Logging Review Comments Addressed

- app/templates/request-code-sent-by-text.html
Presentational changes to 'Sent by Text' page
Added additional class to panel call
Added whitespace replace to mobile number display
https://collaborate2.ons.gov.uk/jira/browse/CR-1578
> Cr 1578 send text

- app/templates/start.html
Add 'Where to find your code' links
Adds where to find your code link urls to /start/
Will be tested by the business in WL/BL (links go to campaign site)
https://collaborate2.ons.gov.uk/jira/browse/CR-1574
> CR-1574 Add 'Where to find your code' links

- app/webchat_handlers.py
- tests/unit/test_webchat_handlers.py
Change to Web Chat opening times
Change Census Saturday and Census Sunday Web Chat closing times
Update unit tests for new values
https://collaborate2.ons.gov.uk/jira/browse/CR-1674
> CR-1674 Web Chat Times

- app/templates/base-cy.html
- app/templates/base-en.html
- app/templates/base-ni.html
- app/templates/support_centre_list_of_centres.html
- scripts/load_templates.sh
- tests/unit/__init__.py
Update the design system to 31.4.16,
Simple change to load_templates script to update version. Minor changes to templates as detailed below. Unfortunately not time to do [CR-1704](https://collaborate2.ons.gov.uk/jira/browse/CR-1704) which was also included in [CR-1710](https://collaborate2.ons.gov.uk/jira/browse/CR-1710) as well as those done below.
Unit tests and cucumber test run against amendments.
https://collaborate2.ons.gov.uk/jira/browse/CR-1690
https://collaborate2.ons.gov.uk/jira/browse/CR-1707
https://collaborate2.ons.gov.uk/jira/browse/CR-1703
> CR-1710_Design system update

- app/templates/start-ni-language-options.html
- app/templates/start-ni-select-language.html
Fix changed link to website
Updated static link in Authentication Journey NI language pages, as content has been moved in website
https://collaborate2.ons.gov.uk/jira/browse/CR-1741
> CR-1741 NI Language Links

- app/utils.py
- tests/unit/test_utils.py
Tweaks to IP extraction to cope with IPv6 values, and update/split of unit tests
Tweaks to IP extraction to cope with IPv6 values, and update/split of unit tests
Changes to ip split and associated unit tests
https://collaborate2.ons.gov.uk/jira/browse/CR-1763
> Cr 1763 i pv6

- scripts/load_templates.sh
Update DS to 31.4.17 (from 31.4.16)
DS version update - doesn't contain any changes that effect RHUI, only updating so all 3 parts of the website are on the same journey so users don't have to load multiple versions
Basic check for issues only
https://collaborate2.ons.gov.uk/jira/browse/CR-1753
> CR-1753 DS Update

- app/templates/macros/ad-lookup/_macro.njk
- app/templates/support_centre_list_of_centres.html
- tests/test_data/ad_lookup/single_return.json
- tests/unit/__init__.py
Fixes issues with display of times for Wednesday, and of 12pm
Change to incorrect call in Wednesday time lookup
Fix to time writeout to cope with 12pm
Updates to test data and unit test variables to better check time outputs
https://collaborate2.ons.gov.uk/jira/browse/CR-1776
> Cr 1776 ad lookup wednesday issues

- app/error_handlers.py
- tests/unit/test_start_handlers.py
Invalidate session on rendering of load shedding page.
Unit tests, cucumber run.
> CR-1809_Load_shedding_invalidate_session
