ONSdigital/census-rh-ui

app/__init__.py
app/eq.py
app/error_handlers.py
app/handlers.py
app/sample.py
app/templates/address-confirmation.html
tests/unit/test_eq.py

A request was made to add a screen to RH for a respondent to be able to confirm an address. This was for a January deadline. Please see screenshot below. This work is covered by user story Cen-0045 Address Confirmation providing traceability to the user requirements.
The RH being run for the LMS pilot has been cloned to this repository and the required page added. I have attempted to use the same css classes and structure as used previously and in EQ, and picked up from the ONS CDN. When the Census branding has been established these class display characteristics can change and hopefully RH and EQ will have the same look and feel and branding.
Previously the respondent was only required to enter a UAC. With the requirement to add further interaction with the respondent state needed to be …

CR-18 CEN-0045 Address Confirmation

---

app/templates/address-edit.html

Simple text change to address-edit page to highlight that functionality required around the respondent selecting not to confirm their address is yet to be analysed. Present page based on original analysis and screen design done in sketch cloud but to be further analysed. At present changed address is sent to EQ but no further action is taken, such as saving the changed address against the original sampled address, case, etc
Address edit page question text changed to "Change of address functionality TBD" from "What is your address?"
On the address confirmation screen select "No, I need to change this address" to bring up the present address edit page.

Text change to highlight address change functionality TBD

---

app/templates/index.html

When entering the UAC in Safari autocorrect was changing one of the set of four characters to a word.
E.g tjwn was being changed to town.
index.html has been changed and spellcheck="false"
Screenshots show what happened what happened before and after. Before the change an error message was displayed and afterwards the questionnaire was presented.
Page before change (tjwn gets autocorrected to town)
Page presented when UAC has been autocorrected (presents an error message)
Page when spellcheck has been set to false
Page presented when UAC has not been autocorrected ( address confirmation screen)

Spellcheck added for UAC

---

app/sample.py
tests/unit/__init__.py
tests/unit/test_eq.py
tests/unit/test_handlers.py

Fix unit tests broken by adding address-confirmation page to respondent home application.
The addition of an address-confirmation and address-edit page required a small degree of restructuring to the code which broke some unit tests. This PR fixes the original unit tests to reflect the changes.  
Run 'make test'. 
In looking into the warnings created running the unit tests the work identified  [technical debt](https://github.com/ONSdigital/respondent-home-ui/issues/85) removing use of a deprecated approach for routing in the aiohttp framework.

Cdtt460 tests unit

---

app/handlers.py
app/templates/404.html
app/templates/base.html
app/templates/closed.html
app/templates/contact-us.html
app/templates/cookies-privacy.html
app/templates/error.html
app/templates/onlinehelp.html
app/templates/partials/footer.html
app/templates/partials/header.html

To align Census Respondent Home with what is currently in EQ census questionnaire for the look of a page. This is only temporary until we know exactly what is required. ( CDTT729)
References to My Study have been replaced by Census Rehearsal 2019 ( text replaced in files).
The ONS logo has been removed.
The colour of the banner has been  changed to purple.
The panel colour has been changed to light purple.
Can be tested locally by running respondent home and going through the pages.

Cdtt727 online help holding page

---

app/eq.py
app/error_handlers.py
app/handlers.py
tests/unit/test_eq.py
tests/unit/test_handlers.py

The application was logging the entire payload of the JWT sent to EQ.  This was a security risk with potentially sensitive data being logged with the associated address, if included in the payload. This logging was removed.  
Minor changes. Logging of JWT payload removed, inspection of logged data to ensure no sensitive data logged. Review of log levels, particularly INFO to avoid clutter in production logs and highlight WARN or ERROR. 
Run unit tests. Check logging when running application.

CDTT-960 Logging Sensitive Data

---

Dockerfile

The principle of using least privilege should be followed when executing code within containers. Specifically, not running as root.
The Dockerfile has been changed:
* Create a dedicated non-root user account for executing the Python code
* Set `python3` as the `ENTRYPOINT` to match the RM Python microservices
I tested this change by creating a differently tagged Docker image and deploying to my Kubernetes cluster. I verified that:
* The pod started successfully
* The Kubernetes readiness and liveness probes succeeded
* There were no errors in the container logs
* `exec`-ing into the container showed the Python process running as the expected non-root user account

Execute Respondent Home under a dedicated non-root user account

---

app/templates/partials/messages.html

As a Respondent I want to the view contact centre information on UAC authentication failure So that I can contact a CC agent. 
The messages.html has been changed to give phone numbers, after error messages, where applicable. The numbers are as follows:
England 
0800 141 2021
Wales 
0800 169 2021
Northern Ireland 
0800 328 2021
Translation 
0800 587 2021 
Run census-rh-ui locally and check that any error messages will show the phone numbers underneath (with the exception of the address confirmation error, which occurs when a user tries to move away from that screen without selecting a bullet point) 
https://collaborate2.ons.gov.uk/jira/browse/CR-115

Cr 115 message for uac auth failure

---

app/templates/partials/footer.html

All links should open in a new tab. What we do link should open ONS What we do instead of household survey information
footer.html has been changed
Run respondent home and click on links in footer. All should open in a new tab

CR_116 - Update what we do link and to open all links in a new tab

---

Pipfile
Pipfile.lock
app/__init__.py
app/app.py
app/config.py
app/handlers.py
app/session.py
tests/unit/__init__.py
tests/unit/test_app.py

Previously, with the addition of an address check page a design decision was taken to store the address information in an encrypted HTTP cookie to avoid fetching the information from RM again when the information was required to send to EQ on confirmation of the address. 
It has since been stipulated any session state should be stored in Redis rather than an encrypted HTTP Cookie. This pull request delivers this change.
The saving of session state was introduced to avoid additional load on RM and possible performance  degradation to the client of making duplicate requests for the same data that would have involved multiple RM services. With the introduction of the census-rh-service the decision could be revisited as to whether to make census-rh-ui stateless and fetch all required data …

CD-56_Persist_session_in_Redis

---

app/handlers.py
tests/unit/test_app.py

Change to shift the starting url of RHUI to '/start' (from '/') to prevent conflicts when site served as part of final website.
Routes for Index, address confirmation and address edit have all been updated to include '/start' at the front of their 'urls' in 'handlers.py'
No refactoring required.
Only required updates to existing tests to include /start
Note that going directly to service root ('/') will now result in a 404 when run locally.
Tests as usual via make test, or manually running.
Visual check of resulting web pages in local version.
None
None

Made switch

---

app/config.py
app/session.py
tests/unit/__init__.py
tests/unit/test_app.py

As recorded [here](https://github.com/aio-libs/aiohttp-session/issues/344) there is an issue with aiohttp-session which leads to what has been termed at the top of the link a _magic session_. We use Redis as the store for session data, only passing a key back to the browser in a cookie. To ensure orphaned session data is not left accumulating in Redis by any unusual client behaviour the max-age parameter is used.
It appears the max-age parameter was used as an idle time-out for the session cookie and redis data. The redis_storage.save_session method calls save_cookie which sets the max-age and recalculates expires on the cookie sent back to the browser. Redis_storage.save_session also resets the expire time of the data in Redis. 
This [behaviour was …

Cr 267 aiohttp session bug

---

app/eq.py
tests/unit/__init__.py

Update to provide EQ with required field and hardcoded value for 'survey'
Addition of hard-coded survey field and value
Updated existing tests

Implement new value for survey in eq launch request

---

app/handlers.py
tests/unit/test_handlers.py

Change to check submitted UAC is in appropriate format
Addition of regex in UAC validation, and matching tests
1 modified and 2 new unit tests added to check for blank and invalid values
None
None

Code update and additional unit tests to regex the uac submission

---

app/__init__.py
app/error_handlers.py
app/handlers.py
app/security.py
tests/unit/__init__.py
tests/unit/test_handlers.py

UAC authentication failure returns HTTP status 401, previously 202. Required for brute force attack protection.
Previously the RH UI consisted of a page to enter the UAC, a page to confirm the address and a page to edit the address. All these pages required the client to have authenticated with a UAC. The existence of the required data in the session, only obtained after a correct UAC was entered, was taken as proof the client had authenticated.
RH UI now contains a mixture of pages where the client may, or may not have authenticated with a UAC. Additionally the pages where the user has not authenticated may also carry session data. The previous method of checking the session for expected data to confirm authentication did not separate the concerns of checking page permissions and …

CR-432 Security enhancements

---

app/eq.py
app/handlers.py
tests/unit/__init__.py
tests/unit/test_eq.py

Where RH has been launched with assistance at an Assisted Digital location the URL query string will carry an 'adlocation' parameter.  The EQ request payload JSON channel and user_id elements and Survey Launched request POST should be set according to this parameter as [documented](https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=CATD&title=Census+Assisted+Digital+solution).
As per the [documented design](https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=CATD&title=Census+Assisted+Digital+solution) changes have been made for Assisted Digital requirements:
- In handlers.py the RH /start/ GET handler stores the 'adlocation' query parameter into the session.
- In handlers.py the saved 'adlocation' query parameter is sent in the POST body …

RH9_Assisted_Digital

---

app/eq.py
app/handlers.py

case['region'] in merged environments is not a single character, so match failing
Updated match to only check first character of case['region']
Unit tests as before
None

Modified region code test to only match first character

---

app/handlers.py
app/templates/timeout.html

Fixed timeout call urls and template
Language parameter for web chat not as Serco want
Timeout template not working correctly
Changed language values from words to code (english > en etc)
Reverted timeout html template to earlier version, fixed urls for /cy and /ni
View source for language code
Via url for timeout
/request-access-code/timeout
/cy/request-access-code/timeout
/ni/request-access-code/timeout
/request-individual-code/timeout
/cy/request-individual-code/timeout
/ni/request-individual-code/timeout

Fix to webchat language value format

---

app/templates/base-cy.html
app/templates/base-en.html
app/templates/base-ni.html
app/templates/base-start-cy.html
app/templates/base-start-en.html
app/templates/base-start-ni.html
scripts/load_templates.sh

Revert cookie banner changes due to conflict
Cookie Banner prevents UAC validation - reverting changes
Previous code removed

CR491 Reversion

---

app/eq.py
app/handlers.py
tests/unit/__init__.py
tests/unit/test_handlers.py

Updates to EQ payload - CR512
EQ language_code for en_US to eo
EQ period_id to 2019
Unit tests updated

EQ Language Code change to 'eo' and period_id change to '2019'

---

app/handlers.py
app/security.py
tests/test_data/rhsvc/uac-cy.json
tests/test_data/rhsvc/uac-ni.json
tests/test_data/rhsvc/uac.json
tests/unit/__init__.py
tests/unit/test_handlers.py

At present the request to RH Service to get details for a UAC uses the UAC as entered by the client with the URL /uacs/{uac}. The RH service hashes the UAC and looks for the UAC details in its repository using the hash. It has been decided to change this behaviour such that the RH UI itself hashes the UAC and makes the request to RH service with the hashed UAC - /uac/{uacHash}.
Minimum changes undertaken to implement required functionality. The join_uac function whose name is a misnomer since the UI was changed from entering the UAC as separate groups, has been renamed uac_hash and returns a hash of the UAC for use in the URL to RH service. I resisted making any unnecessary changes to tidy up the method.
Unit tests changed as required to reflect use of UAC hash. Running the application as …

CR-494 Hash of UAC requested from RH service.

---

app/handlers.py

Messages logged while hitting endpoints now use a custom endpoint name that is language-agnostic. They now store this endpoint and the method in the `event` of the JSON.
Minor refactor of two dictionaries.
Every endpoint now uses a refactored function call, except `/info`.
All endpoints now have a language-agnostic name.
Unit tests run. Visual inspection of logs when endpoints are hit was performed.
https://collaborate2.ons.gov.uk/jira/browse/CR-531

Corrected the message on the endpoint hit logging

---

app/app.py
app/domains.py
app/handlers.py
app/templates/address-edit.html

Fix issue in address-edit error
Moved domain_urls to context_processor (fixes issue, prevents other instances)
Removed existing calls to domain_urls (as now set globally)
Implemented error mark-up for missing first line in modified address
Enter UAC, select no to modify address, blank first line and submit - error should trap correctly

CR536 - Fix address modification error trap, make domains common

---

app/app.py
app/security.py
tests/unit/test_app.py

Remove header changes introduced in 1.46.0, leaving only the GTM updates and client_ip changes
Removed new header changes
Kept updated GTM codes
Kept client_IP changes
Unit tests as normal
Successfully compared this change with release 1.45.0 (previous one) to confirm only required changes are being made
N/A

Header Back-out

---

tests/integration/test_integration.py

RM is removing case[state]. Change removes reference in RHUI integration test
Removed if clause from integration test
https://collaborate2.ons.gov.uk/jira/browse/CR-686

CR-686 Remove case state from RHUI

---

app/start_handlers.py
app/templates/start-region-change.html
tests/unit/__init__.py
tests/unit/test_start_handlers.py

Add a new notification page informing the user that the url/design has been switched when the user enters a UAC with a region value that does not match the current 'display region' ie a NI UAC on the English url
Add new page, and logic to check if it should be displayed depending on current display_region and region value from the case for the UAC entered.
Unit tests are included.
To test manually, enter a ni UAC on the /en/start/ url - page should be displayed.
Requires an update to the RH Cucumber tests to deploy, which is also in review
https://collaborate2.ons.gov.uk/jira/browse/CR-701
https://github.com/ONSdigital/census-rh-cucumber/pull/54

CR 701 Change of Region notification

---

app/requests_handlers.py

Add language switching to fulfilments initial page
Language option now appears on household and individual request initial pages for England and Wales
Also has Cucumber change to remove old test blocking this, which must be deployed first
https://collaborate2.ons.gov.uk/jira/browse/CR-706
https://github.com/ONSdigital/census-rh-cucumber/pull/55

CR-706 Add Language Switching to Fulfilments

---

Pipfile
Pipfile.lock
app/app.py
app/config.py
app/utils.py
tests/unit/__init__.py
tests/unit/test_requests_handlers.py
tests/unit/test_start_handlers.py

To support autoscaling we must ensure that our services will gracefully shutdown. It was discovered during the performance testing in CR-803 by Pete that errors were generated when scaling back the number of RHSvc pods.  I picked up CR-903 to investigate, and found that we needed undertow graceful shutdown to be called, which will be done automatically by Spring Boot 2.3.0 when we upgrade (CR-946).  
Unfortunately pooled (keep-alive) connections are held open between RHUI and RHSvc even when k8s takes terminated pods out of the load-balancer IP tables. So the graceful shutdown at the RHSvc end responds with HTTP 503 or socket-closed back at the RHUI.   
CR-872 was raised to make RHUI tolerate RHSvc shutdown, and this branch implements a fix for this.
The main change is in utils.py where …

Cr 872 retry unlimit connections

---

app/app_logging.py
app/config.py
app/eq.py
app/request.py
app/requests_handlers.py
app/start_handlers.py
app/utils.py
tests/unit/__init__.py
tests/unit/test_requests_handlers.py
tests/unit/test_start_handlers.py

The fix for CR-872 had some deficiencies for the concurrency of the retry attempts and the efficiency of the wait period.
- The request logic has been factored out into an object for the retries.
- The wait mechanism uses the tenacity attibutes.  The time is monkey-patched to 0 for the unit-tests
- The retry logic has been recoded to retry first with pooled connection, then basic connection.
- local testing (duplicating the example from @MartinHumphrey) without an RHSvc and using 2 browsers shows the problem has been fixed at a basic level
- locust testing by scaling back RHSvc shows no errors as before
- checking the RHUI logs from locust testing shows consistent and efficient concurrent behaviour

CR-982 fix retry concurrency

---

app/__init__.py
app/common_handlers.py
app/requests_handlers.py
app/templates/common-resident-or-manager.html
tests/unit/__init__.py
tests/unit/test_requests_handlers_code.py

Adds additional question in CE request journey if selected address is CE Establishment
New common route for asking additional question if address selected by user is a CE and an Establishment to ask if they are a resident or a manager, and build the fulfilment request appropriately.
Unit tests added/updated for CE estab paths
Test by selecting a CE Estab in the address picker, and confirming question appears
No RHCuc update is required
https://collaborate2.ons.gov.uk/jira/browse/CR-994

Cr 994 add ce question

---

app/templates/start-launch-eq.html
app/templates/start.html
scripts/load_templates.sh

Update to design system, and removal of now unnecessary fields
The Design System bug requiring a label on hidden fields has been fixed. This implements the fix in RHUI.
This ups the design system version to 17.3.2
Removes the call params for the label on the 2 hidden field usages
No required unit test or Cucumber updates
Visual check that page still renders with fields removed
Existing unit tests checking for adlocation value still pass
Tested against RHCucumber - no updates required
https://collaborate2.ons.gov.uk/jira/browse/CR-713

CR-713 Fix hidden field implementation

---

app/templates/common-confirm-address.html
app/templates/common-enter-address.html
app/templates/common-select-address.html
app/templates/partials/messages.html

Tweaks to the content (and some positioning) of in page error messages, to align with the Design System
Updates to text of in page messaging
Remove of line of text from error messaging
Some updates to ensure that initial error message appears above the page title in the page (incorrectly positioned on a couple of pages)
Run and trigger an error on the pages (submit form without selection or input, invalid input etc)
https://collaborate2.ons.gov.uk/jira/browse/CR-1075
https://ons-design-system.netlify.app/patterns/error-validation/

Cr 1075 update inline error messages

---

app/templates/start.html

Fixed url on RHUI Start breadcrumb link
The breadcrumb on RHUI Start page is pointing at the wrong url for /en and /cy. This change fixes the issue
Changed url generation to use domain_url parameters
Confirm that the 'home' breadcrumb link goes to the root of the site for /en and /cy (/ni for ni)
https://collaborate2.ons.gov.uk/jira/browse/CR-1146

CR-1146 - Home link bug

---

app/webchat_handlers.py
tests/unit/test_webchat_handlers.py

The RHUI CC opening hours check for Web-Chat is currently incorrect:
- it has old code , based on the rehearsal
- it has hard-coded timezone adjustment for one time period only
- it needs updating for new dates and times
- RH cucumber PR for CR-828 https://github.com/ONSdigital/census-rh-cucumber/pull/81 is currently being reviewed which incorrectly tests to the old date/times. It would be good to have RHUI fixed first.
- made use of timezone **pytz** library for timezone handling
- adjusted times for the new opening date/times as supplied by Ameet
- although the Contact Centre does not open till 10th February 2021 , this is not currently policed. I assume that this is not needed, and is more convenient for continuous testing
- added extra tests across different timezones and years, …

Cr 1152 correct datetime dst

---

app/templates/macros/ad-lookup/_macro.njk
app/templates/macros/time/_macro.njk
app/templates/start.html
app/templates/webchat-form.html
app/webchat_handlers.py
tests/unit/__init__.py
tests/unit/test_webchat_handlers.py

Mostly textual updates for web chat, plus a few tweaks to change the welsh time outputs (am/pm is acceptable in welsh)
Design changes to Web Chat
Web Chat now opens in a full size new window, rather than a pop-up when triggered from RH start
Removal of one category option on the form, and adjustment of some others
Text changes on the form, and 'web chat is closed' page
Updated open/close times to be driven from variables in web chat code to ensure consistency
Update to rhTime macro to cope with 1/2 characters times as well as existing 3/4
Removal of am/pm welsh translations (effects ad Lookup as well), as am/pm is acceptable in welsh
Unit tests have been tweaked to match revised implementation
Requires matching RHCucumber change for text and …

CR-1172 Web Chat Updates

---

app/app.py
app/requests_handlers.py
app/templates/request-common-confirm-name-address.html
app/templates/request-form-sent-post.html
tests/unit/__init__.py
tests/unit/helpers.py
tests/unit/test_requests_handlers_form.py

Adds the ability to request a large print paper form
Addition of check box for large print to the name/address confirmation screen. If ticked, get fulfilment and request fulfilment calls to RHSvc request 'LARGE_PRINT' instead of 'QUESTIONNAIRE'
From /en/requests/paper-form/enter-address/ complete paper form request as before, but tick the new checkbox on the confirm name/address screen
16 new unit tests added
https://collaborate2.ons.gov.uk/jira/browse/CR-1143

Cr 1143 add large print option

---

app/webchat_handlers.py

Value tweak to WebChat code to ensure language value is updated in the Serco iframe call
Changed hard-coded value to use existing 'locale' param instead
Fill in the WebChat form on both english and welsh versions and click 'Start web chat'
View source on next page, checking the url of the iframe call to the timeforstorm url.
The url param 'info_language' should be 'en' for english (and NI) version, and 'cy' for welsh version 
Tested against Cucumber in census-rh-dev - no updates required
https://collaborate2.ons.gov.uk/jira/browse/CR-1292

Cr 1292 web chat welsh bug

---

app/requests_handlers.py
tests/test_data/rhsvc/get_fulfilment_multi_post.json
tests/test_data/rhsvc/get_fulfilment_multi_sms.json
tests/test_data/rhsvc/get_fulfilment_single_post.json
tests/test_data/rhsvc/get_fulfilment_single_sms.json

Fix bug introduced by RHSvc change
An update to RHSvc changed the return value for language in the get_fulfilments call, breaking RHUI when more than one code was returned. This change makes RHUI use the revised values for language.
Request a fulfilment for a welsh postcode (in english or welsh), and confirm journey completes without error
https://collaborate2.ons.gov.uk/jira/browse/CR-1302

CR-1302 Bug fix for request fulfilments

---

app/config.py
app/eq.py
tests/unit/__init__.py

CR-1206 changes to encrypt the EQ payload response_id based on the questionnaire id.  This will match the encryption
done by the services.
existing unit tests will check expected result.

CR-1206 hash eq response_id using salt

---

app/common_handlers.py
app/start_handlers.py
app/templates/common-address-in-england.html
app/templates/common-address-in-northern-ireland.html
app/templates/common-address-in-wales.html
app/templates/start-code-for-england.html
app/templates/start-code-for-northern-ireland.html
app/templates/start-code-for-wales.html

Fixed home links going to the external census websites
Bug fix to resolve the website homepage links in the 'wrong site' pages go to the external sites only.
Update to use 'local' links instead of absolute external ones
Added use of new central contact us links to changed pages
Trigger 'wrong site' pages (NI uAC on /en etc), and confirm homepage link stays on the same site instance
https://collaborate2.ons.gov.uk/jira/browse/CR-1403

CR-1403 Region redirect urls bug

---

app/common_handlers.py
app/requests_handlers.py
app/templates/request-code-nisra-manager.html
app/templates/request-form-nisra-manager.html
tests/unit/__init__.py
tests/unit/helpers.py
tests/unit/test_requests_handlers_access_code.py
tests/unit/test_requests_handlers_form.py

Block all CE Manager fulfilment requests from a 'N' region address
If a user uses the /ni version, selects a NI CE address, and selects that they are a manager, they are shown a page telling them to use the NI Communal Portal.
This only effects 'declared' CE Managers on the /ni version.
It applies to both questionnaire and UAC fulfilments
N Region addresses selected on the /en or /cy sites will be shown the 'wrong site' page as normal
Change implements the above, and removes redundant ce-m-ni unit tests
Start a fulfilment request for an access code or a paper form
Use the ni site version
Select a NI CE address
Select Manager
Get new error page (one for UAC, one for questionnaire)
https://collaborate2.ons.gov.uk/jira/browse/CR-1210

Cr 1210 nisra ce manager restrictions

---

app/common_handlers.py
app/templates/common-enter-address.html
app/utils.py
tests/unit/__init__.py
tests/unit/test_utils.py

Text and error messaging updates to 'enter-address'
Updates to text on page
Updates to error message text, and call in the page
Updates to text in unit tests
Requires matching Cucumber update for error message text change
Check '/en/requests/access-code/enter-address/', '/en/requests/paper-form/enter-address/' and language/region variants for revised text, including tripping errors for empty string and invalid postcode
https://collaborate2.ons.gov.uk/jira/browse/CR-1425
https://github.com/ONSdigital/census-rh-cucumber/pull/107

Cr 1425 updates to enter address

---

app/templates/common-contact-centre.html
tests/unit/__init__.py

Text update and matching unit tests update
Text changes to Call contact centre - Address not found (Register an address)
Text change and unit test update
No Cucumber update required
Trigger an address lookup with a valid postcode, but select 'I cannot find my address' on the address selection screen
https://collaborate2.ons.gov.uk/jira/browse/CR-1426

CR-1426 Update 'address-not-found'

---

app/templates/web-form-success.html
tests/unit/__init__.py

Different text is required in the web-form success page.
Instead of "We will respond to your message within 48 working hours"
it is now "We will respond to you within 2 working days"
Run this branch of RHUI locally and then look at the following pages to see that they contain the new text:
http://localhost:9092/en/web-form/success/
http://localhost:9092/cy/web-form/success/
http://localhost:9092/ni/web-form/success/

CR-1436 change text in web-form-success.html

---

app/templates/404.html

Different text is required in the 404 NOT FOUND error page.
Instead of "If you pasted the web address, check that you copied the entire address."
it is now "If you pasted the web address, check you copied the whole address."
And instead of "If you still encounter problems please contact us. We apologise for any inconvenience this may have caused."
it is now "If the web address is correct or you selected a link or button, contact us for more help."
Run this branch of RHUI locally and then look at the following page, or any other page that won't be found, to see that it contains the new text:
http://localhost:9092/en/start/hello

Cr 1427 Change the Text that's Displayed on the NOT FOUND - 404 error page

---

app/__init__.py
app/common_handlers.py
app/requests_handlers.py
app/templates/common-confirm-address.html
app/templates/common-enter-room-number.html
app/templates/common-resident-or-manager.html
app/templates/common-select-address.html
app/templates/request-code-confirm-mobile.html
app/templates/request-code-enter-mobile.html
app/templates/request-common-confirm-name-address.html
app/templates/request-common-enter-name.html
app/templates/start-ni-language-options.html
app/templates/start-ni-select-language.html
app/templates/webchat-form.html
app/utils.py

Fix error messaging display throughout
Fixes to declaration and display of error messaging throughout to ensure that jump links work correctly
Change should resolve all tests not currently working that are not covered in other PRs
Trigger an error in one of the modified pages, and confirm that the in-page error links jump the page to the start of the error box (and not the top of the field - you should be able to see the red error message at the top of the field)
https://collaborate2.ons.gov.uk/jira/browse/CR-1432

Cr 1432 fix error messaging

---

app/error_handlers.py
app/exceptions.py
app/templates/web-form-too-many-requests.html
app/utils.py
app/web_form_handlers.py
tests/unit/__init__.py
tests/unit/test_web_form_handlers.py

Updates to add clientIP and 429 errors to web form
Updates needed for rate limiting of web form
Added clientIP to RHSvc call
Added handling of a 429 response from RHSvc
Note text has not been finalised
Unit tests have been added, but cannot be tested with RHSvc until RHSvc changes are implemented
https://collaborate2.ons.gov.uk/jira/browse/CR-1478

CR-1478 Web Form Rate Limiting

---

app/config.py
app/google_analytics.py
app/templates/base-cy.html
app/templates/base-en.html
app/templates/base-ni.html
app/templates/base-webchat-cy.html
app/templates/base-webchat-en.html
app/templates/base-webchat-ni.html
app/templates/partials/gtm-no-script.html
app/templates/partials/gtm.html
tests/unit/test_google_analytics.py

Complete
Update to use the changed environment variables for the GTM tagging
Removal of gtm_preview (not required) and gtm_cookies_win (not changing so hardcoded), and addition of GTM_CONTAINER_ID
Update and addition to unit tests
No Cucumber updates required (has been tested)
Run and ensure GTM code is present in pages
https://collaborate2.ons.gov.uk/jira/browse/CR-1521
https://collaborate2.ons.gov.uk/jira/browse/CR-1396

CR-1521 Update GTM tags and envars

---

app/utils.py
tests/unit/test_utils.py

Change to generation of clientIP for rate limiting purposes
clientIP is now passed through a regex to check it only contains ip like content, and to take value third from right instead of the first value.
Added a unit test to check the validity tests
https://collaborate2.ons.gov.uk/jira/browse/CR-1496

Cr 1496 client ip updates

---

app/common_handlers.py
app/templates/common-select-address.html
app/utils.py
tests/unit/__init__.py
tests/unit/helpers.py
tests/unit/test_start_handlers_change_address.py
tests/unit/test_start_handlers_unlinked.py

Changes how 'select-address' page is built to stop WAF rules being violated
Changed radio 'name' to remove problem term 'select'
Removed redundant JSON from radio 'value', so that the field only contains the UPRN value
Added text variant for only 1 address match
Updated effected unit tests
Requires matching RHCuc update due to field name change
Tested in dev
https://collaborate2.ons.gov.uk/jira/browse/CR-1467
https://github.com/ONSdigital/census-rh-cucumber/pull/113

Cr 1467 select address 403 fix

---

app/start_handlers.py

Tweak to transient detection to allow match to value
Tested value does not match value in RM - change so it does
Test for 'transient'
https://collaborate2.ons.gov.uk/jira/browse/CR-1534

CR-1534 Fix Transient

---

app/templates/common-confirm-address.html
app/templates/common-resident-or-manager.html
app/templates/common-select-address.html
app/templates/request-code-confirm-send-by-text.html
app/templates/request-code-household.html
app/templates/request-common-confirm-send-by-post.html
app/templates/start-confirm-address.html
app/templates/start-ni-language-options.html
app/templates/start-transient-accommodation-type.html

Adds 'legends' to radio buttons that didn't have it set already
Calls to onsRadios macro should have 'legends' set
Set 'legends' on onsRadios where not set, also adding 'legendsClasses' hidden class
Removed class on household interstitial page h1
All updated radio fields should now have a 'legend' with a 'u-vh' class, so the legend is visible in the code, but not on the screen (so is read by screen readers).
Existing 'legends' are as before, with a visible legend
https://collaborate2.ons.gov.uk/jira/browse/CR-1566

CR-1566 Radio Legends

---

app/templates/request-code-select-how-to-receive.html
app/templates/request-questionnaire-individual.html
tests/unit/__init__.py
tests/unit/helpers.py
tests/unit/test_request_handlers_access_code.py
tests/unit/test_request_handlers_individual_code.py

Changes to 'select how to receive' hint text
Change of text for both CE and Individual journeys
Unit tests updates to pass through address_type for checking for correct text
Change of button text for individual questionnaires
Check 'Post' option hint text is different for household, CE and Individuals (both household and CE variants) in the access code journey
https://collaborate2.ons.gov.uk/jira/browse/CR-1581
https://collaborate2.ons.gov.uk/jira/browse/CR-1584

Cr 1584 update post option text

---

app/request_handlers.py

Invalidates the user session when a fulfilment is successfully completed
Added the 'invalidate' call to the render of the 'success' pages in all fulfilment journeys to kill off the users session. This prevents the session continuing if they wish to make further requests
Make a fulfilment request, and ensure that the user session is removed from the browser when reaching the 'success' screen
https://collaborate2.ons.gov.uk/jira/browse/CR-1499

Cr 1499 fulfilment session invalidate

---

app/eq.py
tests/unit/__init__.py

Change EQ period ID to 2021
Change value for EQ period_id to 2021, and matching test value
https://collaborate2.ons.gov.uk/jira/browse/CR-1657

CR-1657 Change EQ Period ID

---

app/common_handlers.py
app/templates/common-enter-room-number.html
tests/unit/helpers.py
tests/unit/test_request_handlers_access_code.py
tests/unit/test_request_handlers_questionnaire.py

Removes the empty validation on room number
Removal of check and error for an empty room number
Removal of matching unit tests
Request a fulfilment for a CE. On Confirm Address click 'Add room number'. Add value, and click continue. Click change room number, blank the value and continue. Validation should allow an empty value, and the value should be removed from the Confirm Address screen
https://collaborate2.ons.gov.uk/jira/browse/CR-1586

CR-1586 Make Room Number Optional

---

app/__init__.py
app/templates/start.html
tests/unit/test_start_handlers.py

Fix to UAC input to ensure correct error message is displayed
Change to make the 2 possible error messages on the uac input box trigger correctly
Test 1: Submit an empty UAC field - error message above UAC input panel should be 'Enter an access code'
Test 2: Enter a partial or invalid UAC into the field (not empty, but not 16 characters, or containing symbols)- error message should now be 'Enter a valid access code'
https://collaborate2.ons.gov.uk/jira/browse/CR-1573

CR-1573 Start Invalid Message

---

app/config.py

Up timeout to 45 minutes
Increases the session timeout to 45 minutes
Updated the session timeout values in the config.py
Start a session in RH. View the RH_SESSION cookie, and check that it will expire in 45 minutes.
https://collaborate2.ons.gov.uk/jira/browse/CR-1664

CR-1664 Increase Session Timeout

---

app/templates/start.html

Removes the start page Web Chat link
Removed Web Chat button in Start page - Web Chat can now only be reached directly
Cucumber update already deployed
Check 'start' - check Web chat button is removed
https://collaborate2.ons.gov.uk/jira/browse/CR-1608

CR-1608 Remove Web Chat Link

---

app/app.py
app/common_handlers.py
app/error_handlers.py
app/handlers.py
app/request.py
app/request_handlers.py
app/security.py
app/session.py
app/start_handlers.py
app/support_centre_handlers.py
app/trace.py
app/utils.py
app/web_form_handlers.py
app/webchat_handlers.py
tests/unit/__init__.py
tests/unit/test_error_handlers.py
tests/unit/test_session.py
tests/unit/test_trace.py
tests/unit/test_utils.py

Enable logs to be filtered to associate previous log statements generated from an individual client and provide context in investigating client errors, warnings.
Middleware has been introduced so that for every request a client_id and trace are added to the request object and available to log statements.
The trace is taken from the X-Cloud-Trace-Context header which is added to a request by Google and has the specification `X-Cloud-Trace-Context: TRACE_ID/SPAN_ID;o=TRACE_TRUE`. A trace is unique to a client request and is used to group logs within a client request process. A span would represent a unit of work within a trace, if for instance we were using OpenTelemetry or OpenCensus client libraries to instrument the code and generate logs and metrics and display latency data in Cloud …

CR-1456 Add log identifier

---

app/__init__.py
app/error_handlers.py
app/exceptions.py
app/start_handlers.py
tests/unit/__init__.py
tests/unit/test_start_handlers.py

Revert/update code to generate a 401 error when an invalid UAC is entered on /start
Changed UI response to RHSvc 404 on get_uac to trigger new error_handler that returns the start page, but triggers a 401 error
Enter invalid UAC. Check browser gets a 401 error. Check 401 error is logged
https://collaborate2.ons.gov.uk/jira/browse/CR-1724

Cr 1724 add uac 401 trap

---

app/templates/base-ni.html

Remove Accessible formats link from NI footer.
Simple change to remove footer for NI as above.
Unit tests and cucumber run as check
JIRA: https://collaborate2.ons.gov.uk/jira/browse/CR-1730

CR-1730 NI footer

---

app/utils.py
tests/unit/__init__.py

Increase postcode endpoint limit
Increase the results per page limit to the maximum of 5000 for the AIMS rh/postcode endpoint call. Change to increase amount of results for large postcodes (Universities)
Use a large results postcode in the fulfilment journey 'enter address' page, and check results in the 'select address' page
CV4 7AL, CV4 7ES
https://collaborate2.ons.gov.uk/jira/browse/CR-1751

Cr 1751 increase postcode limit

---

app/utils.py
tests/unit/helpers.py
tests/unit/test_request_handlers_questionnaire.py

Change isnumeric to ~~isdigit~~ isdecimal
The current 'isnumeric' test in 'number of people in household' allows non-integer numbers (superscript, foreign language numbers etc) - changing to ~~isdigit~~ isdecimal which only allows integers
Check page still functions and doesn't work with non integers 'numbers'
https://collaborate2.ons.gov.uk/jira/browse/CR-1761
Explanation of the difference: https://lerner.co.il/2019/02/17/pythons-str-isdigit-vs-str-isnumeric/

CR-1761 Number of People Issue

---

app/request_handlers.py
tests/unit/test_session.py

Some fulfilment journey pages are missing the session check (because they didn't call from the session), but this means they work for direct access, and don't get rejected. This adds missing session checks
Session checks added to code and questionnaire household pages, select how to receive and questionnaire individual. Note that check has not been added to code individual as this already had checks because it can be an entry point
Session unit tests updated to include updated pages
Try direct access of 
/en/request/paper-questionnaire/household/
/en/request/paper-questionnaire/individual/
/en/request/access-code/household/
and language variants - should fall with a session message
https://collaborate2.ons.gov.uk/jira/browse/CR-1770

Cr 1770 add missing session check

---

app/security.py
tests/unit/test_app.py

Tweak to CSP settings to prevent dropout
Change to the urls in the CSP settings to match EQ and website, that should prevent dropout, and update to matching unit tests
Andy Pitt will validate update in WL
https://collaborate2.ons.gov.uk/jira/browse/CR-1769

Cr 1769 csp update

---

app/start_handlers.py

UAC input has had a nonetype error returned - change strengthens the value test
Expands 'empty test' of UAC input to include none-type return
Open /en/start/
Right click the uac input box and select 'inspect'
Delete the input box in the inspector so that the input box disappears on screen
Submit the form
Page should return the empty field error
https://collaborate2.ons.gov.uk/jira/browse/CR-1745

Cr 1745 uac none type

---

app/error_handlers.py
app/request.py
tests/unit/helpers.py
tests/unit/test_start_handlers.py
tests/unit/test_web_form_handlers.py

Reduce the high number of misleading error logs for situations where a request was legitimately rate limited.
Client responses to RHUI with HTTP status 429 have been reduced from being logged as an error to a warn.
Unit tests amended. Cucumber run.
JIRA: https://collaborate2.ons.gov.uk/jira/browse/CR-1766

CR-1766_Reduce_HTTP_429_responses_to_warn

---

app/request.py
tests/unit/helpers.py
tests/unit/test_start_handlers.py
tests/unit/test_web_form_handlers.py

RH Svc replies with a HTTP 400 BAD REQUEST for requests to link a UAC form type to an ineligible case type. As a bad request response is legitimate in this instance and not an error the make_request function no longer automatically logs bad request responses as an error. It leaves the calling code to handle the raised exception and log appropriately if an error. If the calling code does not handle the raised exception, the error_handlers.py HTTP Bad Request override will cause the response_error function to be triggered and an error logged that can be linked in the logs to the original make_request log now at info level.
Logging level of HTTP 400 responses lowered to info in generic make_request function. Units tests amended as appropriate.
Unit tests run, RH cucumber tests passed.
JIRA: …

Cr 1754 uac case incompatible logging

---

app/templates/partials/gtm.html
scripts/load_templates.sh

DS Update to enable tweak to GTM code javascript
DS Update
Adjustment to GTM javascript to enable tracking to work as soon as cookie button is clicked
Need to update local DS version for test
Check no unwanted side effects (business will sign off GTM update)
https://collaborate2.ons.gov.uk/jira/browse/CR-1800

Cr 1800 ds gtm update

---

app/common_handlers.py
app/request_handlers.py
app/start_handlers.py
app/utils.py
app/web_form_handlers.py
app/webchat_handlers.py
tests/unit/__init__.py
tests/unit/helpers.py
tests/unit/test_request_handlers_access_code.py
tests/unit/test_request_handlers_continuation.py
tests/unit/test_request_handlers_individual_code.py
tests/unit/test_request_handlers_questionnaire.py
tests/unit/test_start_handlers_transient.py
tests/unit/test_web_form_handlers.py
tests/unit/test_webchat_handlers.py

Adds trapping for spaces only and removal of leading/trailing spaces in non-regex checked fields
Update to response validation for first name, last name in all 'Enter name' pages (all postal fulfilment journeys)
Update to response validation for town name in transient journey
Update to response validation for 'add room number' in CE fulfilment journeys (note room number field can be empty, but should disregard just spaces)
Update to response validation for web form 'name' field
Update to response validation for web chat 'screen name' field
New and updated unit tests for above
Other text fields in the authentication and fulfilment journeys do not require an update as they are covered by their existing regexes
Try entering just spaces in the fields - check that …

Cr 1826 fix name field spaces

---

app/utils.py
tests/unit/test_utils.py

Addition of unicode normalize to convert non-standard numbers so they can be processed by AIMS
Addition of line to process postcode input and convert non-standard digits to be readable by AIMS
Confirm that postcode BS２ ０FW works with AIMS, and all normal postcodes still work
https://collaborate2.ons.gov.uk/jira/browse/CR-1833

CR-1833 Fix for postcodes with unicode data

---

app/webchat_handlers.py
tests/unit/test_webchat_handlers.py

Change Web Chat Monday to Friday opening time to 10am.
Simple change to variable where week day opening time held. Unit tests amended.
Run unit tests. Run updated cucumber tests.
Associated cucumber update: https://github.com/ONSdigital/census-rh-cucumber/pull/131
hots

CR-1850 Web Chat opening times

---

app/webchat_handlers.py
tests/unit/test_webchat_handlers.py

Change Web Chat Monday to Friday opening time to 10am.
Simple change to variable where week day opening time held. Unit tests amended.
Run unit tests. Run updated cucumber tests.
Associated cucumber update: https://github.com/ONSdigital/census-rh-cucumber/pull/131

CR-1850 Web Chat opening times take 2
